### PR TITLE
fix: more logs for /notify calls

### LINKED ISSUE #42: fix: add more logging to /notify calls
Adding more logs so that we have more insights into what's happening

### PR DESCRIPTION
**Pull request by Rakowskiii**
# Description
Adding more logs so that we can debug easier.

Resolves #42 

## How Has This Been Tested?

Only adding logs, no testing required.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/handlers/notify.rs [hunk 1]
```diff
@@ -92,11 +92,18 @@ pub async fn handler(
 
         let id = chrono::Utc::now().timestamp_millis().unsigned_abs();
 
+        let topic = sha256::digest(&*hex::decode(data.sym_key)?);
+
+        info!(
+            "message to {}, on topic: {} with message_id: {}",
+            data.id, &topic, id
+        );
+
```
Comment (arein) [inline src/handlers/notify.rs:101]: can you add the `account` as well so it's easer to look up? and `client_id`?

**Review by arein — APPROVED** [review]

File: src/handlers/notify.rs (hunk 1 above)
Comment (Rakowskiii) [reply src/handlers/notify.rs]: Data.id is `account`. Added `client_id`
