### PR TITLE
fix: recconnect to relay after error

### LINKED ISSUE #76: Send the data about wsclient errors to grafana - alarm on client problems
Untill we migrate to webhooks, Cast's functionality is highly dependant on websocket client. It's crucial for it to be alive, otherwise no new subscriptions, unsubscriptions or updates can happen. 

It should be monitored and alarmed on.

### PR DESCRIPTION
**Pull request by Rakowskiii**
# Description

Small change adding reconnection logic after error form relay.

Resolves #76 

## How Has This Been Tested?

Tested with force-closing and restarting local relay.
image

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/websocket_service/mod.rs [hunk 1]
```diff
@@ -72,6 +72,10 @@ impl WebsocketService {
                 }
                 wsclient::RelayClientEvent::Error(e) => {
                     warn!("Received error from relay: {}", e);
+                    while let Err(e) = self.connect().await {
+                        warn!("Error reconnecting to relay: {}", e);
```
Comment (arein) [inline src/websocket_service/mod.rs:76]:
```suggestion
                        error!("Error reconnecting to relay: {}", e);
```

**Review by arein — APPROVED** [review]
The relay disconnects clients every 5mins

We'll need to evolve this over time to reconnect without "warn" statements but not urgent

File: src/websocket_service/mod.rs (hunk 1 above)
Comment (Rakowskiii) [reply src/websocket_service/mod.rs]: The regular reconnection was already handled, this is only about sudden ones
