### PR TITLE
fix: resubscribe to topics after recconnect

### LINKED ISSUE #63: Cast not registering users with wc_pushSubscribe
After investigation with Cali and Celine, turns out that the new implementation of relay client is not automatically resubscribing to all topics, leading to Cast stopping listening for subscriptions after 10min of project registering.

### PR DESCRIPTION
**Pull request by Rakowskiii**
# Description

In the investigation we found out, that after 10 minutes Cast stops listening to old subscribe topics.
This behaviour was caused by relay not persisting this data over multiple connections, and dropping the connection every 10 min (for load balancing).
To solve this, Cast needs to resubscribe to all topics it knows on each reconnect (which this PR is re-introducing after change from it's own wsclient to our own relay client).

This could use a test for the future (to see if after reconnecting it's still working), but we are starting the migration of the communication with relay from websockets to http next week.

# Solution
After reconnecting to relay Cast needs to resubscribe to all topics to be able to listen to incoming messages (for subscribing, unsubscribing and updating subscriptions)

Resolves #63 

## How Has This Been Tested?

Integration tests. Verified manually that it's resubscribing to all topics.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

File: src/websocket_service/mod.rs [hunk 1]
```diff
@@ -112,6 +119,57 @@ async fn handle_msg(
...
+        })
+        .await;
+
+    let cursor = database
+        .collection::<ProjectData>("project_data")
+        .find(None, None)
+        .await?;
+
+    cursor
+        .chunks(500)
```
Comment (heilhead) [inline src/websocket_service/mod.rs:157]: You can use the const from from the `relay_rpc`:
https://github.com/WalletConnect/WalletConnectRust/blob/main/relay_rpc/src/rpc.rs#L27

File: src/websocket_service/mod.rs [hunk 2]
```diff
@@ -112,6 +119,57 @@ async fn handle_msg(
...
+async fn resubscribe(
+    database: &Arc<Database>,
+    client: &Arc<relay_client::websocket::Client>,
+) -> Result<()> {
+    info!("Resubscribing to all topics");
+    // Get all topics from db
+    let cursor = database
+        .collection::<LookupEntry>("lookup_table")
+        .find(None, None)
+        .await?;
```
Comment (heilhead) [inline src/websocket_service/mod.rs:131]: Depending on how many topics there are, you may need to set up some pagination?

File: src/websocket_service/mod.rs (hunk 1 above)
Comment (Rakowskiii) [reply src/websocket_service/mod.rs]: Done, good catch, thanks!

File: src/websocket_service/mod.rs (hunk 2 above)
Comment (Rakowskiii) [reply src/websocket_service/mod.rs:131]: Good idea, will leave it for separate PR thought, as I want to first merge this, as it currently broken.
Made an issue: https://github.com/WalletConnect/cast-server/issues/65
